import type { ApiOperation } from "../types";
import { dateRange, op, pageCount } from "./helpers";

export const CATALOG_OPS: ApiOperation[] = [
  op({
    operationId: "products.list",
    title: "List products",
    description:
      "Paginated merchant product catalog. Do not send outlet_ids (500). name= does not filter.",
    method: "GET",
    host: "pos",
    pathTemplate: "/api/v5/products",
    sourceDocument: "products.md",
    evidence: "observed",
    authProfile: "bearer",
    responseKind: "json",
    safety: "read",
    tags: ["products", "catalog"],
    exposed: true,
    inputSchema: {
      type: "object",
      properties: {
        page: { type: "integer" },
        count: { type: "integer" },
        name: { type: "string", description: "Echoed only; does not filter in capture" },
      },
      required: ["page", "count"],
      additionalProperties: false,
    },
  }),
  op({
    operationId: "products.searchAjax",
    title: "Product typeahead search",
    description: "Same-origin ajax typeahead that filters by name.",
    method: "GET",
    host: "merchant",
    pathTemplate: "/ajax/products/get",
    sourceDocument: "products.md",
    evidence: "observed",
    authProfile: "cookie-csrf",
    responseKind: "json",
    safety: "read",
    tags: ["products", "search"],
    exposed: true,
    inputSchema: {
      type: "object",
      properties: { name: { type: "string" } },
      required: ["name"],
      additionalProperties: false,
    },
  }),
  op({
    operationId: "customers.get",
    title: "Get customer",
    description: "Single customer profile by id.",
    method: "GET",
    host: "pos",
    pathTemplate: "/api/v5/customers/{customer_id}",
    sourceDocument: "customers.md",
    evidence: "observed",
    authProfile: "bearer",
    responseKind: "json",
    safety: "read",
    tags: ["customers"],
    exposed: true,
    inputSchema: {
      type: "object",
      properties: { customer_id: { type: "integer" } },
      required: ["customer_id"],
      additionalProperties: false,
    },
  }),
  op({
    operationId: "inventories.stockHistories",
    title: "Inventory stock histories",
    description:
      "Paginated stock movements for one inventory/variant at an outlet. Auth uses raw token (no Bearer).",
    method: "GET",
    host: "pos",
    pathTemplate: "/api/v5/inventories/{inventory_id}/stock-histories",
    sourceDocument: "inventories-stock-histories.md",
    evidence: "observed",
    authProfile: "raw-token",
    responseKind: "json",
    safety: "read",
    tags: ["inventory", "stock"],
    exposed: true,
    inputSchema: {
      type: "object",
      properties: {
        inventory_id: { type: "integer" },
        page: { type: "integer" },
        count: { type: "integer" },
        outlet_ids: { type: "string" },
        type: {
          type: "string",
          description:
            "CSV: sales,purchase,transfer,adjustment-plus,adjustment-minus,refund",
        },
        sort: { type: "string" },
      },
      required: ["inventory_id", "page", "count", "outlet_ids", "type"],
      additionalProperties: false,
    },
  }),
  op({
    operationId: "inventories.stockTurnover",
    title: "Stock turnover picker",
    description:
      "Outlet variants with on-hand stock and last-touch dates (adjustment form picker).",
    method: "GET",
    host: "pos",
    pathTemplate: "/api/v5/inventories/stock-turnover",
    sourceDocument: "stock-adjustment.md",
    evidence: "observed",
    authProfile: "bearer",
    responseKind: "json",
    safety: "read",
    tags: ["inventory", "stock-adjustment"],
    exposed: true,
    inputSchema: {
      type: "object",
      properties: {
        outlet_ids: { type: "string" },
        page: { type: "integer" },
        count: { type: "integer" },
        sort: { type: "string" },
        search: { type: "string" },
      },
      required: ["outlet_ids", "page", "count", "sort"],
      additionalProperties: false,
    },
  }),
  op({
    operationId: "purchases.list",
    title: "List purchases",
    description: "Paginated purchase orders.",
    method: "GET",
    host: "pos",
    pathTemplate: "/api/v5/purchases",
    sourceDocument: "purchases.md",
    evidence: "observed",
    authProfile: "bearer",
    responseKind: "json",
    safety: "read",
    tags: ["purchases"],
    exposed: true,
    inputSchema: {
      ...pageCount,
      properties: {
        ...pageCount.properties,
        outlet_ids: { type: "string" },
      },
    },
  }),
  op({
    operationId: "purchases.items",
    title: "Purchase line items",
    description: "Line items for one PO.",
    method: "GET",
    host: "pos",
    pathTemplate: "/api/v5/purchases/{purchase_id}/items",
    sourceDocument: "purchases.md",
    evidence: "observed",
    authProfile: "bearer",
    responseKind: "json",
    safety: "read",
    tags: ["purchases"],
    exposed: true,
    inputSchema: {
      type: "object",
      properties: {
        purchase_id: { type: "string" },
        outlet_id: { type: "integer" },
      },
      required: ["purchase_id", "outlet_id"],
      additionalProperties: false,
    },
  }),
  op({
    operationId: "users.list",
    title: "List users",
    description: "Paginated staff list with access catalog.",
    method: "GET",
    host: "pos",
    pathTemplate: "/api/v5/users",
    sourceDocument: "users.md",
    evidence: "observed",
    authProfile: "bearer",
    responseKind: "json",
    safety: "read",
    tags: ["users"],
    exposed: true,
    inputSchema: {
      type: "object",
      properties: {
        page: { type: "integer" },
        count: { type: "integer" },
        name: { type: "string" },
        outlet_ids: { type: "string" },
        outlet_ids_filter: { type: "string" },
        access: { type: "string" },
      },
      required: ["page", "count"],
      additionalProperties: false,
    },
  }),
  op({
    operationId: "order.histories.web",
    title: "Order histories (web)",
    description: "Paginated sales history grouped by day.",
    method: "GET",
    host: "order",
    pathTemplate: "/api/v5/order/histories/web",
    sourceDocument: "order-histories-web.md",
    evidence: "observed",
    authProfile: "bearer",
    responseKind: "json",
    safety: "read",
    tags: ["orders", "sales"],
    exposed: true,
    inputSchema: {
      type: "object",
      properties: {
        page: { type: "integer" },
        count: { type: "integer" },
        ...dateRange,
        settle_by: { type: "string" },
        invoice_number: { type: "string" },
        customer_id: { type: "integer" },
      },
      required: ["page", "count", "start_date", "end_date", "outlet_ids"],
      additionalProperties: false,
    },
  }),
  op({
    operationId: "order.histories.legacy",
    title: "Order history detail (legacy)",
    description: "Single-sale receipt detail.",
    method: "GET",
    host: "order",
    pathTemplate: "/api/v5/order/histories/{sales_id}/legacy",
    sourceDocument: "order-histories-legacy.md",
    evidence: "observed",
    authProfile: "bearer",
    responseKind: "json",
    safety: "read",
    tags: ["orders", "sales"],
    exposed: true,
    inputSchema: {
      type: "object",
      properties: { sales_id: { type: "integer" } },
      required: ["sales_id"],
      additionalProperties: false,
    },
  }),
  op({
    operationId: "order.histories.installment",
    title: "Order histories (installment)",
    description: "Installment/credit sales. Empty capture — guard pagination/agg.",
    method: "GET",
    host: "order",
    pathTemplate: "/api/v5/order/histories/installment",
    sourceDocument: "order-histories-installment.md",
    evidence: "empty-response",
    authProfile: "bearer",
    responseKind: "json",
    safety: "read",
    tags: ["orders", "installment"],
    exposed: true,
    inputSchema: {
      type: "object",
      properties: {
        page: { type: "integer" },
        count: { type: "integer" },
        ...dateRange,
        customer_id: { type: "integer" },
      },
      required: ["page", "count", "start_date", "end_date", "outlet_ids"],
      additionalProperties: false,
    },
  }),
];
