import type { ApiOperation } from "../types";
import { op } from "./helpers";

export const MISC_OPS: ApiOperation[] = [
  op({
    operationId: "payments.pending",
    title: "Pending payments",
    description: "Payment pending list.",
    method: "GET",
    host: "payment",
    pathTemplate: "/api/v1/payments/pending",
    sourceDocument: "routes.md",
    evidence: "observed",
    authProfile: "bearer",
    responseKind: "json",
    safety: "read",
    tags: ["payments"],
    exposed: true,
    inputSchema: {
      type: "object",
      properties: {
        page: { type: "integer" },
        start_date: { type: "string" },
        end_date: { type: "string" },
        invoice_number: { type: "string" },
        status: { type: "string" },
      },
      additionalProperties: false,
    },
  }),
  op({
    operationId: "payments.pendingAttributes",
    title: "Pending payment attributes",
    description: "Pending payment attribute filters.",
    method: "GET",
    host: "payment",
    pathTemplate: "/api/v1/payments/pending/attributes",
    sourceDocument: "routes.md",
    evidence: "observed",
    authProfile: "bearer",
    responseKind: "json",
    safety: "read",
    tags: ["payments"],
    exposed: true,
    inputSchema: {
      type: "object",
      properties: { is_read: { type: "string" }, status: { type: "string" } },
      additionalProperties: false,
    },
  }),
  op({
    operationId: "reminders.products",
    title: "Product reminders",
    description: "Product reminder list.",
    method: "GET",
    host: "pos",
    pathTemplate: "/api/v5/reminders/products",
    sourceDocument: "routes.md",
    evidence: "observed",
    authProfile: "bearer",
    responseKind: "json",
    safety: "read",
    tags: ["products", "reminders"],
    exposed: true,
    inputSchema: {
      type: "object",
      properties: {
        count: { type: "integer" },
        page: { type: "integer" },
        outlet_ids: { type: "string" },
        type: { type: "string" },
      },
      additionalProperties: false,
    },
  }),
  op({
    operationId: "customers.survey",
    title: "Customer survey responses",
    description: "Customer survey list.",
    method: "GET",
    host: "pos",
    pathTemplate: "/api/v5/customers/survey",
    sourceDocument: "routes.md",
    evidence: "observed",
    authProfile: "bearer",
    responseKind: "json",
    safety: "read",
    tags: ["customers", "survey"],
    exposed: true,
    inputSchema: {
      type: "object",
      properties: {
        count: { type: "integer" },
        page: { type: "integer" },
        outlet_ids: { type: "string" },
        start_date: { type: "string" },
        end_date: { type: "string" },
      },
      additionalProperties: false,
    },
  }),
  op({
    operationId: "customers.surveySetting",
    title: "Customer survey settings",
    description: "Customer survey configuration.",
    method: "GET",
    host: "pos",
    pathTemplate: "/api/v5/customers/survey/setting",
    sourceDocument: "routes.md",
    evidence: "observed",
    authProfile: "bearer",
    responseKind: "json",
    safety: "read",
    tags: ["customers", "survey"],
    exposed: true,
    inputSchema: { type: "object", properties: {}, additionalProperties: false },
  }),
  op({
    operationId: "ingredients.listAjax",
    title: "Ingredients list (ajax)",
    description: "Ingredients & recipes ajax list.",
    method: "GET",
    host: "merchant",
    pathTemplate: "/ajax/product/ingredients",
    sourceDocument: "routes.md",
    evidence: "observed",
    authProfile: "cookie-csrf",
    responseKind: "json",
    safety: "read",
    tags: ["ingredients"],
    exposed: true,
    inputSchema: {
      type: "object",
      properties: {
        count: { type: "integer" },
        page: { type: "integer" },
        outlet_ids: { type: "string" },
        search: { type: "string" },
        status_stock: { type: "string" },
      },
      additionalProperties: false,
    },
  }),
  op({
    operationId: "ingredients.recipesTotalAjax",
    title: "Ingredients recipes total",
    description: "Ingredients-recipes total ajax.",
    method: "GET",
    host: "merchant",
    pathTemplate: "/ajax/product/ingredients-recipes/total",
    sourceDocument: "routes.md",
    evidence: "observed",
    authProfile: "cookie-csrf",
    responseKind: "json",
    safety: "read",
    tags: ["ingredients"],
    exposed: true,
    inputSchema: { type: "object", properties: {}, additionalProperties: false },
  }),
  op({
    operationId: "account.menuAccess",
    title: "Menu access",
    description: "Chrome menu access by role.",
    method: "GET",
    host: "account",
    pathTemplate: "/api/v1/menu/access",
    sourceDocument: "routes.md",
    evidence: "observed",
    authProfile: "bearer",
    responseKind: "json",
    safety: "read",
    tags: ["chrome", "account"],
    exposed: true,
    inputSchema: {
      type: "object",
      properties: { role_id: { type: "integer" } },
      additionalProperties: false,
    },
  }),
  op({
    operationId: "suppliers.listHtml",
    title: "List suppliers (HTML)",
    description: "SSR suppliers directory. No working JSON list — scrape HTML table.",
    method: "GET",
    host: "merchant",
    pathTemplate: "/suppliers",
    sourceDocument: "suppliers.md",
    evidence: "observed",
    authProfile: "cookie-csrf",
    responseKind: "html",
    safety: "read",
    tags: ["suppliers", "html"],
    exposed: true,
    inputSchema: {
      type: "object",
      properties: {
        name: { type: "string" },
        phone: { type: "string" },
        location: { type: "string" },
        page: { type: "integer" },
      },
      additionalProperties: false,
    },
  }),
  op({
    operationId: "stockAdjustment.historyHtml",
    title: "Stock adjustment history (HTML)",
    description: "SSR stock adjustment history table.",
    method: "GET",
    host: "merchant",
    pathTemplate: "/stock/adjustment",
    sourceDocument: "stock-adjustment.md",
    evidence: "observed",
    authProfile: "cookie-csrf",
    responseKind: "html",
    safety: "read",
    tags: ["stock-adjustment", "html"],
    exposed: true,
    inputSchema: {
      type: "object",
      properties: {
        searchdate: { type: "string" },
        variant: { type: "string" },
        sort: { type: "string" },
        type_product: { type: "string" },
        page: { type: "integer" },
      },
      additionalProperties: false,
    },
  }),
];

export const MUTATION_OPS: ApiOperation[] = [
  op({
    operationId: "products.inventories.bulk",
    title: "Bulk stock adjustment save",
    description: "POST bulk inventory adjustments. Mutates stock.",
    method: "POST",
    host: "pos",
    pathTemplate: "/api/v5/products/inventories/bulk",
    sourceDocument: "stock-adjustment.md",
    evidence: "documented-not-executed",
    authProfile: "bearer",
    responseKind: "json",
    safety: "write",
    tags: ["stock-adjustment", "mutation"],
    exposed: true,
    inputSchema: {
      type: "object",
      properties: {
        data: {
          type: "array",
          items: {
            type: "object",
            properties: {
              variant_id: { type: "integer" },
              product_id: { type: "integer" },
              outlet_id: { type: "integer" },
              stock: { type: "integer" },
              notes: { type: "string" },
              stock_min: { type: "integer" },
              track_stock: { type: "boolean" },
            },
          },
        },
      },
      required: ["data"],
      additionalProperties: false,
    },
  }),
  op({
    operationId: "purchases.confirmation",
    title: "Confirm purchase receive",
    description: "Finish PO receive. Mutates stock.",
    method: "POST",
    host: "pos",
    pathTemplate: "/api/v5/purchases/confirmation",
    sourceDocument: "purchases.md",
    evidence: "documented-not-executed",
    authProfile: "bearer",
    responseKind: "json",
    safety: "write",
    tags: ["purchases", "mutation"],
    exposed: true,
    inputSchema: {
      type: "object",
      properties: {
        purchase_id: { type: "string" },
        outlet_id: { type: "integer" },
        is_modified_price: { type: "boolean" },
        items: { type: "array", items: { type: "object" } },
      },
      required: ["purchase_id", "outlet_id", "items"],
      additionalProperties: false,
    },
  }),
  op({
    operationId: "purchases.cancel",
    title: "Cancel purchase order",
    description:
      "Cancel PO via GET ajax. Semantically destructive despite GET verb.",
    method: "GET",
    host: "merchant",
    pathTemplate: "/ajax/purchase/cancel/{id}",
    sourceDocument: "purchases.md",
    evidence: "documented-not-executed",
    authProfile: "cookie-csrf",
    responseKind: "json",
    safety: "destructive",
    tags: ["purchases", "mutation"],
    exposed: true,
    inputSchema: {
      type: "object",
      properties: { id: { type: "string" } },
      required: ["id"],
      additionalProperties: false,
    },
  }),
];
