/**
 * Builds the widget SPA (widgets/) into one HTML file and regenerates src/widgets/bundled.ts:
 *   bun run widgets:bundle
 * Run it after changing anything under widgets/src, widgets/dev, widgets/index.html,
 * widgets/vite.config.ts, widgets/tsconfig.json, src/widgets/contract.ts, package.json or bun.lock.
 * tests/unit/widgets-bundle.test.ts fails while the committed bundle is stale.
 */
import { execFileSync } from "node:child_process";
import { readFileSync, writeFileSync } from "node:fs";
import path from "node:path";
import { VIEW_MARKER } from "../src/widgets/contract";
import { computeWidgetSourceHash } from "./lib/widget-source-hash";

const root = path.resolve(import.meta.dirname, "..");
const hash = computeWidgetSourceHash(root);

execFileSync("bun", ["run", "widgets:build"], { cwd: root, stdio: "inherit" });

const built = readFileSync(path.join(root, "widgets", "dist", "index.html"), "utf8");
const head = /<head(\s[^>]*)?>/i.exec(built);
if (!head) throw new Error("widgets/dist/index.html has no <head> element");
const insertAt = head.index + head[0].length;
const html = `${built.slice(0, insertAt)}\n    <meta name="mj-build" content="${hash.slice(0, 12)}" />${built.slice(insertAt)}`;

const markers = html.split(VIEW_MARKER).length - 1;
if (markers !== 1) {
  throw new Error(`Expected ${VIEW_MARKER} exactly once in the widget HTML, found ${markers}`);
}

const out = [
  "/** Widget SPA for ui://manujujaya/* resources. Generated by scripts/bundle-widgets.ts; do not edit. */",
  `export const WIDGET_SOURCE_HASH = ${JSON.stringify(hash)};`,
  `export const WIDGET_HTML: string = ${JSON.stringify(html)};`,
  "",
].join("\n");
writeFileSync(path.join(root, "src", "widgets", "bundled.ts"), out);
console.log(`Wrote src/widgets/bundled.ts (${html.length} chars, source hash ${hash.slice(0, 12)})`);
