/**
 * Regenerates src/docs/bundled.ts from docs/*.md (the API docs served as
 * qasir://docs/* resources). Run after editing any API doc:
 *   bun run scripts/bundle-docs.ts
 * tests/unit/docs-pii.test.ts fails when the bundle drifts from docs/.
 */
import { readFileSync, writeFileSync } from "node:fs";
import path from "node:path";
import { API_DOC_NAMES } from "../src/registry/doc-endpoints";

const root = path.resolve(import.meta.dirname, "..");
const lines = API_DOC_NAMES.map((name) => {
  const md = readFileSync(path.join(root, "docs", `${name}.md`), "utf8");
  return `  ${JSON.stringify(name)}: ${JSON.stringify(md)},`;
});
const out = [
  "/** Bundled docs for MCP resources (sanitized on read). Generated by scripts/bundle-docs.ts; do not edit. */",
  "export const BUNDLED_DOCS: Record<string, string> = {",
  ...lines,
  "};",
  "",
].join("\n");
writeFileSync(path.join(root, "src", "docs", "bundled.ts"), out);
console.log(`Wrote ${API_DOC_NAMES.length} docs to src/docs/bundled.ts`);
